version: '3.8'

services:
  api_gateway:
    build: 
      context: ./api-gateway
      dockerfile: Dockerfile.dev
    container_name: api-gateway
    ports:
      - "3001:3001"
    volumes:
      - ./api-gateway/src:/usr/src/app/src
      - /usr/src/app/node_modules
    depends_on:
      - user_service
    networks:
      - app-network

  user_service:
    build: 
      context: ./user-service
      dockerfile: Dockerfile.dev
    container_name: user-service
    ports:
      - "3002:3002"
    volumes:
      - ./user-service/src:/usr/src/app/src
      - /usr/src/app/node_modules
      - ./user-service/prisma/dev.db:/usr/src/app/prisma/dev.db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
