version: '3.8'

services:
  api_gateway:
    build: 
      context: ./api-gateway
      dockerfile: Dockerfile.dev
    container_name: api-gateway
    ports:
      - "3001:3001"
    volumes:
      - ./api-gateway/src:/usr/src/app/src
      - /usr/src/app/node_modules
    depends_on:
      - user_service
    networks:
      - app-network

  user_service:
    build: 
      context: ./user-service
      dockerfile: Dockerfile.dev
    container_name: user-service
    ports:
      - "3002:3002"
    volumes:
      - ./user-service/src:/usr/src/app/src
      - /usr/src/app/node_modules
      - ./user-service/prisma/dev.db:/usr/src/app/prisma/dev.db
    networks:
      - app-network

  advertisement_service:
    build: 
      context: ./advertisement-service
      dockerfile: Dockerfile.dev
    container_name: advertisement-service
    ports:
      - "3003:3003"
    volumes:
      - ./advertisement-service/src:/usr/src/app/src
      - /usr/src/app/node_modules
      - ./advertisement-service/prisma/dev.db:/usr/src/app/prisma/dev.db
    networks:
      - app-network

  kafka:
    image: bitnami/kafka:latest
    restart: on-failure
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_NUM_PARTITIONS=3
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - app-network

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - app-network

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    depends_on:
      - kafka
      - zookeeper
    ports:
      - "8080:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=alura
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    networks:
      - app-network
      
networks:
  app-network:
    driver: bridge
